name: WeChat Status Monitor

on:
  schedule:
    # 每分钟运行一次 (注意: GitHub Actions最小间隔是5分钟)
    - cron: '*/5 * * * *'
  
  # 允许手动触发
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run WeChat Monitor
      env:
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        python monitor.py
        
    - name: Commit status file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add last_status.json || true
        git commit -m "Update status file [skip ci]" || true
        git push || true
